// <auto-generated />
namespace MailGames.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class RankingMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RankingMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201312111231259_RankingMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
